### ISSUE TITLE
Edit text field in svg files

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/linuxmuster-artwork#14]
In most of the svg files the text fields are not editable (only very few). Which software was used to create these files? I've tried Inkscape, but could edit the texts.

**Comment by MachtDochNix** [comment]
Did you mean not edit? 
I use Inkscape as described in the wiki. Currently version 1.0. So the correct version in the wiki should be version 0.92 or 1.0.

As for the texts, there were problems in read the docs with the SVG if they contained text fields. Therefore the conversion into paths.

**Comment by zefanja** [comment]
Yes, most of the text fields are paths and not textfields anymore. I like to translate some of the graphics. Do you have the original files with textfields?

**Comment by MachtDochNix** [comment]
No, unfortunately I did not think that far. :-(

If you tell me which ones would be of more interest to you, then I would try to make them for you in that form.

Think about the possibility to keep text fields and their paths in separate layers. Do you think it is worth the effort?

**Comment by MachtDochNix** [comment]
I thought about the problem, what I had in mind as a solution would be:

Place the texts in the SVGs on an extra layer. Example:

- Copy of "Text fields de" as paths *2
- "Text fields de" (for editing)
- Copy of "Text fields en" as paths *1 
- "Text fields en" (for editing)
- Graphical elements (lowest level) *1 *2

*1 -> Save these layers as visible for English documentation
*2 -> same as *1 for German documentation.

My question to you is: How could such multilingual media be arranged in Read The Docs of the respective language? 

#####

Ich habe über das Problem nachgedacht, was mir als Lösung vorschwebt, wäre:

Die Texte in den SVGs auf eine extra Ebene zu platzieren. Beispiel:

- Kopie von "Textfelder de" als Pfade *2
- "Textfelder de" (zur Bearbeitung)
- Kopie von "Textfelder en" als Pfade *1 
- "Textfelder en" (zur Bearbeitung)
- Grafische Elemente (unterste Ebene) *1 *2

*1 -> Speicherung dieser Ebenen als Sichtbar für Englische Dokumentation
*2 -> wie *1 für deutsche Dokumentation.

Meine Frage an dich wie ließen sich solche mehrsprachlichen Medien dann in Read The Docs der betreffenden Sprache zu ordnen?

**Comment by zefanja** [comment]
I've re-created the text field. I'm not sure yet, how to integrate them in read the docs, but there is a way.
