### ISSUE TITLE
Add linuxmuster.net logo

### ISSUE THREAD

**Issue by dorianim** [linuxmuster/linuxmuster-artwork#16]
I think it would make sense to add the linuxmutser.net logo, so everything is in one place :)
(for example from over here: https://wiki.linuxmuster.net/verein/artwork )

**Comment by MachtDochNix** [comment]
Yes, you are absolutely right. It's still a construction site.

**Comment by MachtDochNix** [comment]
If you need a graphic for your work on the Linbo GUI let me know.
